  type: imageToVideo
  name: 图片转视频
  parameters:
   - key: image_folder
     name: 图片存储根目录
     type: string
   - key: saveFile
     name: 保存路径
     type: string
   - key: image_endswith
     name: 图片后缀名(.jpg,.png...)
     type: string
   - key: fps
     name: 设置视频帧
     type: Float
     default: 1

