type: videoConcat
name: 视频拼接
parameters: 
  - key: vinFile
    name: 视频文件路径
    type: string
  - key: subinFile
    name: 字幕文件路径
    type: string    
  - key: saveFile
    name: 保存路径
    type: string
  - key: subParam
    name: 字幕设置
    children: 
    - key: font
      name: 字体
      type: string
    - key: fontsize
      name: 字体大小
      type: int
      default: 60 