  type: videoEditor
  name: 视频编辑
  parameters:
   - key: inFile
     name: 源文件路径
     type: list
   - key: saveFile
     name: 保存路径
     type: string
   - key: subclipStart
     name: 剪辑开始时间
     type: int
   - key: subclipEnd
     name: 剪辑结束时间
     type: int
   - key: resizeWidth
     name: 视频宽度
     type: int
   - key: resizeHeight
     name: 视频高度
     type: int
   - key: soundMultiple
     name: 声音大小
     type: float