  type: videoEditor
  name: 视频编辑
  parameters:
   - key: inFile
     name: 视频文件路径
     type: string
   - key: saveFile
     name: 保存路径
     type: string
   - key: subParam
     name: 字幕属性
     children:
      - key: txt
        name: 文本内容
        type: string
      - key: txt_width
        name: 文本显示宽度
        type: float
        default: 视频宽度
      - key: txt_color
        name: 字体颜色
        type: string
      - key: font
        name: 字体
        type: string
      - key: font_size
        name: 字体大小
        type: float
      - key: stroke_color
        name: 描边颜色
        type: string
      - key: stroke_width
        name: 描边宽度
        type: float
        default: 1.5
      - key: gap
        name: 文本列间距
        type: Float
        default: 20
      - key: sub_hight
        name: 展示字幕高度
        type: Float
        default: 视频高度
      - key: sub_width
        name: 展示字幕宽度
        type: Float
        default: 视频宽度
      - key: x_start
        name: 字幕横轴开始位置
        type: Float
        default: 0
      - key: y_start
        name: 字幕纵轴开始位置
        type: Float
        default: 0
      - key: x_speed
        name: 字幕横轴速度
        type: Float
        default: 0
      - key: y_speed
        name: 字幕纵轴速度
        type: Float
        default: 10
      

      
  