type: videoEditor
name: 视频编辑
parameters:
  - key: inFile
    name: 源文件路径
    type: string
  - key: saveFile
    name: 保存路径
    type: string
  - key: subclip
    name: 剪辑长度
    children:
    - key: subclipStart
      name: 剪辑开始时间
      type: int
    - key: subclipEnd
      name: 剪辑结束时间
      type: int
  - key: speed
    name: 速度调整
    children:      
    - key: speedFactor
      name: 倍速
      type: float
    - key: speedDuration
      name: 视频总长
      type: float
  - key: resize
    name: 尺寸调整
    children:         
    - key: resizeNewsize
      name: 新尺寸
      type: any #tuple, float, function
    - key: resizeWidth
      name: 视频宽度
      type: int
    - key: resizeHeight
      name: 视频高度
      type: int
  - key: crop
    name: 视频裁剪
    children:       
    - key: crop_x1
      name: 左上角x
      type: int
    - key: crop_y1
      name: 左上角y
      type: int
    - key: crop_x2
      name: 右下角x
      type: int
    - key: crop_y2
      name: 右下角y
      type: int
    - key: crop_x_center
      name: 中心x坐标
      type: int
    - key: crop_y_center
      name: 中心y坐标
      type: int     
    - key: crop_w
      name: 视频宽度
      type: int           
    - key: crop_h
      name: 视频高度
      type: int
  - key: rotate
    name: 视频旋转
    children:  
    - key: rotAngle
      name: 旋转角度
      type: int
    - key: rotUnit
      name: 单位
      type: singleSelect
      options:
      - value: deg
        label: degree
      - value: rad
        label: radians
  - key: margin
    name: 页边距
    children:  
    - key: mar_all
      name: 外边框宽度像素
      type: int
    - key: mar_l
      name: 左边框宽度
      type: int
      default: 0 
    - key: mar_r
      name: 右边框宽度
      type: int
      default: 0 
    - key: mar_t
      name: 上边框宽度
      type: int      
      default: 0 
    - key: mar_b
      name: 下边框宽度
      type: int     
      default: 0 
    - key: marColor
      name: 边框颜色
      type: tuple
      default: (0, 0, 0)
    - key: opacity
      name: 边框透明度
      type: float 
      default: 1.0
