  type: videoEditor
  name: 视频编辑
  parameters:
   - key: inFile
     name: 视频文件路径
     type: string
   - key: saveFile
     name: 保存路径
     type: string
   - key: blur_radius
     name: 模糊半径
     type: Int
     default: 25
   - key: fps
     name: 视频标记帧数
     type: float
   - key: tmptxt
     name: 手动标记坐标保存文本文件
     type: string
     